name: Deploy FastAPI to Cloud Run

on:
    workflow_run:
      workflows: ["Deploy Terraform to GCP"]
      types:
        - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker to Google Cloud
        run: echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},DATASET_ID=desafio_latam,TABLE_ID=latam
