name: Deploy FastAPI to Cloud Run

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate with service account
        env:
            GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
            echo "$GCP_SA_KEY" | base64 --decode > ${HOME}/gcloud-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json
            gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Verify Authentication
        run: gcloud auth print-access-token

      - name: Build and push Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcf-artifacts/fastapi-app:latest .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcf-artifacts/fastapi-app:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-app \
          --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcf-artifacts/fastapi-app:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},DATASET_ID=desafio_latam,TABLE_ID=latam
