name: Deploy Terraform to GCP

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -var="google_credentials=${{ secrets.GCP_SA_KEY }}"
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="google_credentials=${{ secrets.GCP_SA_KEY }}"
        working-directory: ./terraform
